### ISSUE TITLE
GLOBAL tags cannot be used

### ISSUE THREAD

**Issue by fxqy** [vinsworldcom/nppQuickText#10]
Saved in the profile, but not on the Options interface, and cannot be used with ctrl-Enter

**Comment by vinsworldcom** [comment]
Yes, I've noticed this too.  As this is someone else's code that I just modified, I'm not clear on what's causing the issue.  I'll have to look at it when I have some time.  If you have a proposed solution, feel free to open a PR.

Cheers.

**Comment by fxqy** [comment]
I didn't solve it. I can't write C code

**Comment by vinsworldcom** [comment]
A temp solution is to hack the QuickText.ini file manually and add the global section.  In notepad.exe (something other than Notepad++ so a save on exit won't overwrite) add a section:

[255]
shortcut1=expansion1
shortcut2=expansion2

and so on where shortcut# is your tag and expansion# is the expansion after typing the tag and the "hotkey" (e.g., CTRL-Enter).  This works for me, but then remember you can't edit the Global tags in the GUI.

It seems when editing the Global tags in the GUI, it's writing them to the output file with the next array value (86) instead of the special Global tag value (255).  Probably an array index thing in C++ just enumerating and not recognizing Global as special and not just the next array index.

Cheers.

**Comment by vinsworldcom** [comment]
Fixed c36aab9
