### ISSUE TITLE
\t TAB key simulation is demanded

### ISSUE THREAD

**Issue by mikered2** [vinsworldcom/nppQuickText#22]
like \n I need \t to simulate TAB key press. i like to code python blocks identation with tab and not with spaces.

**Comment by vinsworldcom** [comment]
I can look into it, but you'll need to edit the QuickText.ini file manually - you won't be able to use the "Setting" menu to add TAB as TAB key cannot be entered in the text box control - it just switches to the next control on the Settings window.  Using a literal '\t' in the text box will be a literal '\t'.  I don't think trying to guess user intent in the Settings dialog is worth it.

Currently, when reading the QuickText.ini file, I change "\n" to actual carriage return / line feeds as per the document's EOL setting.  I think that may be the correct way to to "\t" as well - query the TAB setting (keep tabs or expand) and treat accordingly.

Cheers.

**Comment by vinsworldcom** [comment]
Actually, just tested and you can cut / paste a TAB into the Settings "Substitution Text" text box.  So you can just type in the text you want, cut / paste TABs instead of 4 or however many spaces and it not only saves correctly into the QuickText.ini file, but when you use the Tags, they insert TABs correctly into the doc.  I just tested for Makefile which requires TABs, not spaces for indents.

Cheers.

**Comment by mikered2** [comment]
Thumbs Up.Thanks

**Comment by vinsworldcom** [comment]
No fix needed.

**Comment by vinsworldcom** [comment]
You can also use `Ctrl+Tab` in the "Substitution Text" box in Settings to insert a tab character.
